AWSTemplateFormatVersion: "2010-09-09"
Description: >
  DuckStore Shopping SPA - S3 Static Hosting with CloudFront CDN.
  CloudFront acts as reverse proxy for both static assets (S3) and API calls (YARP Gateway).

Parameters:
  Environment:
    Type: String
    Default: production
    AllowedValues:
      - production
      - staging
    Description: Deployment environment

  ApiGatewayOriginDomain:
    Type: String
    Default: "placeholder.example.com"
    Description: >
      Domain name of the YARP API Gateway (e.g., api.duckstore.com or ALB DNS name).
      CloudFront will forward /catalog-service/*, /ordering-service/*, /basket-service/* to this origin.
      Use the default placeholder while the API Gateway is not yet deployed — update once it is live.

  ApiGatewayOriginProtocol:
    Type: String
    Default: https-only
    AllowedValues:
      - https-only
      - http-only
    Description: Protocol to use when connecting to the API Gateway origin

  CognitoRedirectUrl:
    Type: String
    Default: ""
    Description: >
      (Optional) Cognito redirect URL override. If empty, the CloudFront distribution URL will be used.

  CustomDomain:
    Type: String
    Default: "shop.thecodeduck.com"
    Description: >
      Custom domain for the SPA (e.g., shop.thecodeduck.com).
      Leave empty to use the default CloudFront domain (*.cloudfront.net).

  Route53HostedZoneId:
    Type: String
    Default: ""
    Description: >
      Route 53 Hosted Zone ID for the custom domain.
      Required when CustomDomain is set.
      Find it at: AWS Console → Route 53 → Hosted zones → thecodeduck.com → Hosted zone ID.

Conditions:
  HasCustomRedirectUrl: !Not
    - !Equals
      - !Ref CognitoRedirectUrl
      - ""

  HasCustomDomain: !And
    - !Not [ !Equals [ !Ref CustomDomain, "" ] ]
    - !Not [ !Equals [ !Ref Route53HostedZoneId, "" ] ]

Resources:
  # ──────────────────────────────────────────────
  # S3 Bucket — Static assets
  # ──────────────────────────────────────────────
  SpaBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "duckstore-spa-${Environment}-${AWS::AccountId}"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      VersioningConfiguration:
        Status: Enabled
      LifecycleConfiguration:
        Rules:
          - Id: CleanupOldVersions
            Status: Enabled
            NoncurrentVersionExpiration:
              NoncurrentDays: 30
      Tags:
        - Key: Project
          Value: DuckStore
        - Key: Component
          Value: Shopping-SPA
        - Key: Environment
          Value: !Ref Environment

  # ──────────────────────────────────────────────
  # S3 Bucket Policy — CloudFront OAC access only
  # ──────────────────────────────────────────────
  SpaBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref SpaBucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: AllowCloudFrontOAC
            Effect: Allow
            Principal:
              Service: cloudfront.amazonaws.com
            Action: s3:GetObject
            Resource: !Sub "${SpaBucket.Arn}/*"
            Condition:
              StringEquals:
                "AWS:SourceArn": !Sub "arn:aws:cloudfront::${AWS::AccountId}:distribution/${CloudFrontDistribution}"

  # ──────────────────────────────────────────────
  # ACM Certificate — custom domain (must be us-east-1)
  # ──────────────────────────────────────────────
  SpaAcmCertificate:
    Type: AWS::CertificateManager::Certificate
    Condition: HasCustomDomain
    Properties:
      DomainName: !Ref CustomDomain
      ValidationMethod: DNS
      DomainValidationOptions:
        - DomainName: !Ref CustomDomain
          HostedZoneId: !Ref Route53HostedZoneId
      Tags:
        - Key: Project
          Value: DuckStore
        - Key: Component
          Value: Shopping-SPA
        - Key: Environment
          Value: !Ref Environment

  # ──────────────────────────────────────────────
  # CloudFront Origin Access Control (OAC)
  # ──────────────────────────────────────────────
  CloudFrontOAC:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        Name: !Sub "duckstore-spa-oac-${Environment}"
        Description: OAC for DuckStore SPA S3 bucket
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4

  # ──────────────────────────────────────────────
  # CloudFront Managed Policy IDs for API behaviors
  #   CachingDisabled:              4135ea2d-6df8-44a3-9df3-4b5a84be39ad
  #   AllViewerExceptHostHeader:    b689b0a8-53d0-40ab-baf2-68738e2966ac
  # These replace custom policies — no caching, all headers
  # (including Authorization) forwarded to the YARP Gateway.
  # ──────────────────────────────────────────────

  # ──────────────────────────────────────────────
  # CloudFront Response Headers Policy
  # ──────────────────────────────────────────────
  SecurityHeadersPolicy:
    Type: AWS::CloudFront::ResponseHeadersPolicy
    Properties:
      ResponseHeadersPolicyConfig:
        Name: !Sub "duckstore-spa-security-headers-${Environment}"
        Comment: Security headers for DuckStore SPA
        SecurityHeadersConfig:
          ContentTypeOptions:
            Override: true
          FrameOptions:
            FrameOption: DENY
            Override: true
          ReferrerPolicy:
            ReferrerPolicy: strict-origin-when-cross-origin
            Override: true
          StrictTransportSecurity:
            AccessControlMaxAgeSec: 31536000
            IncludeSubdomains: true
            Preload: true
            Override: true
          XSSProtection:
            ModeBlock: true
            Override: true
            Protection: true

  # ──────────────────────────────────────────────
  # CloudFront Function — SPA routing
  # Rewrites non-asset paths to /index.html so
  # Angular router handles client-side routes.
  # Unlike CustomErrorResponses, this only affects
  # the S3 (default) behavior — API 403/404 pass through.
  # ──────────────────────────────────────────────
  SpaRoutingFunction:
    Type: AWS::CloudFront::Function
    Properties:
      Name: !Sub "duckstore-spa-routing-${Environment}"
      AutoPublish: true
      FunctionConfig:
        Comment: Rewrite non-asset paths to /index.html for Angular SPA routing
        Runtime: cloudfront-js-2.0
      FunctionCode: |
        function handler(event) {
          var request = event.request;
          var uri = request.uri;

          // Do not rewrite API routes; let them pass through to their origins.
          var apiPrefixes = [
            '/catalog-service/',
            '/ordering-service/',
            '/basket-service/',
            '/api/'
          ];
          for (var i = 0; i < apiPrefixes.length; i++) {
            var prefix = apiPrefixes[i];
            if (uri.startsWith(prefix)) {
              return request;
            }
          }

          // Determine file extension from the last path segment only.
          var lastSlashIndex = uri.lastIndexOf('/');
          var lastSegment = lastSlashIndex >= 0 ? uri.substring(lastSlashIndex + 1) : uri;
          var dotIndex = lastSegment.lastIndexOf('.');
          var extension = dotIndex >= 0 ? lastSegment.substring(dotIndex + 1).toLowerCase() : '';

          // Known static asset extensions that should NOT be rewritten.
          var staticExtensions = [
            'js', 'css', 'html', 'htm', 'json',
            'png', 'jpg', 'jpeg', 'gif', 'svg', 'ico',
            'txt', 'map',
            'woff', 'woff2', 'ttf', 'eot', 'otf',
            'xml', 'webmanifest'
          ];

          var isAsset = false;
          if (extension) {
            for (var j = 0; j < staticExtensions.length; j++) {
              if (extension === staticExtensions[j]) {
                isAsset = true;
                break;
              }
            }
          }

          // If the request is not for a known static asset, serve index.html for SPA client-side routing.
          if (!isAsset) {
            request.uri = '/index.html';
          }
          return request;
        }

  # ──────────────────────────────────────────────
  # CloudFront Distribution
  # ──────────────────────────────────────────────
  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Comment: !Sub "DuckStore Shopping SPA (${Environment})"
        Enabled: true
        HttpVersion: http2and3
        DefaultRootObject: index.html
        PriceClass: PriceClass_100

        Aliases: !If
          - HasCustomDomain
          - - !Ref CustomDomain
          - !Ref AWS::NoValue

        ViewerCertificate: !If
          - HasCustomDomain
          - AcmCertificateArn: !Ref SpaAcmCertificate
            SslSupportMethod: sni-only
            MinimumProtocolVersion: TLSv1.2_2021
          - CloudFrontDefaultCertificate: true

        # ── Origins ──
        Origins:
          # S3 Origin (static files)
          - Id: S3Origin
            DomainName: !GetAtt SpaBucket.RegionalDomainName
            OriginAccessControlId: !Ref CloudFrontOAC
            S3OriginConfig:
              OriginAccessIdentity: ""

          # API Gateway Origin (YARP backend)
          - Id: ApiGatewayOrigin
            DomainName: !Ref ApiGatewayOriginDomain
            CustomOriginConfig:
              HTTPPort: 80
              HTTPSPort: 443
              OriginProtocolPolicy: !Ref ApiGatewayOriginProtocol
              OriginSSLProtocols:
                - TLSv1.2

        # ── Default behavior → S3 (SPA static files) ──
        DefaultCacheBehavior:
          TargetOriginId: S3Origin
          ViewerProtocolPolicy: redirect-to-https
          Compress: true
          # Managed-CachingOptimized policy
          CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6
          ResponseHeadersPolicyId: !Ref SecurityHeadersPolicy
          AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
          CachedMethods:
            - GET
            - HEAD
          FunctionAssociations:
            - EventType: viewer-request
              FunctionARN: !GetAtt SpaRoutingFunction.FunctionARN

        # ── API behaviors → YARP API Gateway ──
        CacheBehaviors:
          # /catalog-service/*
          - PathPattern: "/catalog-service/*"
            TargetOriginId: ApiGatewayOrigin
            ViewerProtocolPolicy: redirect-to-https
            CachePolicyId: 4135ea2d-6df8-44a3-9df3-4b5a84be39ad
            OriginRequestPolicyId: b689b0a8-53d0-40ab-baf2-68738e2966ac
            AllowedMethods:
              - GET
              - HEAD
              - OPTIONS
              - PUT
              - POST
              - PATCH
              - DELETE
            Compress: true

          # /ordering-service/*
          - PathPattern: "/ordering-service/*"
            TargetOriginId: ApiGatewayOrigin
            ViewerProtocolPolicy: redirect-to-https
            CachePolicyId: 4135ea2d-6df8-44a3-9df3-4b5a84be39ad
            OriginRequestPolicyId: b689b0a8-53d0-40ab-baf2-68738e2966ac
            AllowedMethods:
              - GET
              - HEAD
              - OPTIONS
              - PUT
              - POST
              - PATCH
              - DELETE
            Compress: true

          # /basket-service/*
          - PathPattern: "/basket-service/*"
            TargetOriginId: ApiGatewayOrigin
            ViewerProtocolPolicy: redirect-to-https
            CachePolicyId: 4135ea2d-6df8-44a3-9df3-4b5a84be39ad
            OriginRequestPolicyId: b689b0a8-53d0-40ab-baf2-68738e2966ac
            AllowedMethods:
              - GET
              - HEAD
              - OPTIONS
              - PUT
              - POST
              - PATCH
              - DELETE
            Compress: true

      Tags:
        - Key: Project
          Value: DuckStore
        - Key: Component
          Value: Shopping-SPA
        - Key: Environment
          Value: !Ref Environment

  # ──────────────────────────────────────────────
  # Route 53 — A record (alias) → CloudFront
  # ──────────────────────────────────────────────
  SpaDnsRecord:
    Type: AWS::Route53::RecordSet
    Condition: HasCustomDomain
    Properties:
      HostedZoneId: !Ref Route53HostedZoneId
      Name: !Ref CustomDomain
      Type: A
      AliasTarget:
        DNSName: !GetAtt CloudFrontDistribution.DomainName
        # CloudFront hosted zone ID — always this fixed value
        HostedZoneId: Z2FDTNDATAQYW2
        EvaluateTargetHealth: false

Outputs:
  S3BucketName:
    Description: Name of the S3 bucket for SPA static files
    Value: !Ref SpaBucket
    Export:
      Name: !Sub "duckstore-spa-bucket-${Environment}"

  S3BucketArn:
    Description: ARN of the S3 bucket
    Value: !GetAtt SpaBucket.Arn

  CloudFrontDistributionId:
    Description: CloudFront distribution ID (needed for cache invalidation)
    Value: !Ref CloudFrontDistribution
    Export:
      Name: !Sub "duckstore-spa-cf-distribution-id-${Environment}"

  CloudFrontDomainName:
    Description: CloudFront distribution domain name
    Value: !GetAtt CloudFrontDistribution.DomainName

  CloudFrontUrl:
    Description: Full URL to access the SPA (CloudFront default domain)
    Value: !Sub "https://${CloudFrontDistribution.DomainName}"

  SpaUrl:
    Description: Primary URL to access the SPA (custom domain if configured)
    Value: !If
      - HasCustomDomain
      - !Sub "https://${CustomDomain}"
      - !Sub "https://${CloudFrontDistribution.DomainName}"

  CognitoRedirectUrl:
    Description: URL to configure in Cognito as allowed callback/redirect
    Value: !If
      - HasCustomRedirectUrl
      - !Ref CognitoRedirectUrl
      - !If
        - HasCustomDomain
        - !Sub "https://${CustomDomain}"
        - !Sub "https://${CloudFrontDistribution.DomainName}"
