AWSTemplateFormatVersion: "2010-09-09"
Description: >
  IAM Role for GitHub Actions OIDC — DuckStore SPA Deploy.
  Allows the GitHub Actions workflow to assume this role without
  storing long-lived AWS credentials as secrets.

Parameters:
  GitHubOrg:
    Type: String
    Description: GitHub organization or username (e.g., myorg or myusername)

  GitHubRepo:
    Type: String
    Description: GitHub repository name (e.g., DuckStore)

  AllowedBranch:
    Type: String
    Default: "main"
    Description: Branch allowed to assume this role (use * to allow all branches)

Resources:
  # ──────────────────────────────────────────────
  # GitHub OIDC Identity Provider
  # Only needs to be created once per AWS account.
  # If it already exists, comment this resource out.
  # ──────────────────────────────────────────────
  GitHubOIDCProvider:
    Type: AWS::IAM::OIDCProvider
    Properties:
      Url: https://token.actions.githubusercontent.com
      ClientIdList:
        - sts.amazonaws.com
      # Thumbprints for GitHub Actions OIDC provider at token.actions.githubusercontent.com.
      # Source: GitHub OIDC / AWS configuration docs:
      #   https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/about-security-hardening-with-openid-connect
      # GitHub may rotate these certificates; verify and update these thumbprints periodically.
      ThumbprintList:
        - 6938fd4d98bab03faadb97b34396831e3780aea1
        - 1c58a3a8518e8759bf075b76b750d4f2df264fcd

  # ──────────────────────────────────────────────
  # IAM Role — assumed by GitHub Actions
  # ──────────────────────────────────────────────
  GitHubActionsDeployRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "duckstore-spa-github-deploy-${GitHubRepo}"
      Description: Assumed by GitHub Actions to deploy DuckStore SPA
      MaxSessionDuration: 3600
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: AllowGitHubOIDC
            Effect: Allow
            Principal:
              Federated: !GetAtt GitHubOIDCProvider.Arn
            Action: sts:AssumeRoleWithWebIdentity
            Condition:
              StringEquals:
                "token.actions.githubusercontent.com:aud": sts.amazonaws.com
              StringLike:
                # Allows: push to branch, workflow_dispatch, and scheduled runs
                "token.actions.githubusercontent.com:sub":
                  - !Sub "repo:${GitHubOrg}/${GitHubRepo}:ref:refs/heads/${AllowedBranch}"
                  - !Sub "repo:${GitHubOrg}/${GitHubRepo}:environment:production"
                  - !Sub "repo:${GitHubOrg}/${GitHubRepo}:environment:staging"
      Policies:
        - PolicyName: SpaDeploy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              # CloudFormation — deploy/read stacks
              - Sid: CloudFormation
                Effect: Allow
                Action:
                  - cloudformation:CreateStack
                  - cloudformation:UpdateStack
                  - cloudformation:DeleteStack
                  - cloudformation:DescribeStacks
                  - cloudformation:DescribeStackEvents
                  - cloudformation:DescribeStackResource
                  - cloudformation:DescribeStackResources
                  - cloudformation:GetTemplate
                  - cloudformation:ListStackResources
                  - cloudformation:ValidateTemplate
                  - cloudformation:CreateChangeSet
                  - cloudformation:ExecuteChangeSet
                  - cloudformation:DeleteChangeSet
                  - cloudformation:DescribeChangeSet
                Resource:
                  - !Sub "arn:aws:cloudformation:*:${AWS::AccountId}:stack/duckstore-spa-*"

              # S3 — upload static assets
              - Sid: S3Deploy
                Effect: Allow
                Action:
                  - s3:PutObject
                  - s3:GetObject
                  - s3:DeleteObject
                  - s3:ListBucket
                  - s3:GetBucketLocation
                Resource:
                  - !Sub "arn:aws:s3:::duckstore-spa-*"
                  - !Sub "arn:aws:s3:::duckstore-spa-*/*"

              # CloudFront — invalidate cache
              - Sid: CloudFrontInvalidation
                Effect: Allow
                Action:
                  - cloudfront:CreateInvalidation
                  - cloudfront:GetDistribution
                  - cloudfront:GetInvalidation
                  - cloudfront:ListDistributions
                Resource: "*"

              # CloudFront — create/update distribution (for CloudFormation)
              - Sid: CloudFrontManage
                Effect: Allow
                Action:
                  - cloudfront:CreateDistribution
                  - cloudfront:UpdateDistribution
                  - cloudfront:DeleteDistribution
                  - cloudfront:TagResource
                  - cloudfront:CreateOriginAccessControl
                  - cloudfront:DeleteOriginAccessControl
                  - cloudfront:GetOriginAccessControl
                  - cloudfront:UpdateOriginAccessControl
                  - cloudfront:CreateCachePolicy
                  - cloudfront:DeleteCachePolicy
                  - cloudfront:GetCachePolicy
                  - cloudfront:UpdateCachePolicy
                  - cloudfront:CreateOriginRequestPolicy
                  - cloudfront:DeleteOriginRequestPolicy
                  - cloudfront:GetOriginRequestPolicy
                  - cloudfront:UpdateOriginRequestPolicy
                  - cloudfront:CreateResponseHeadersPolicy
                  - cloudfront:DeleteResponseHeadersPolicy
                  - cloudfront:GetResponseHeadersPolicy
                  - cloudfront:UpdateResponseHeadersPolicy
                  - cloudfront:CreateFunction
                  - cloudfront:UpdateFunction
                  - cloudfront:DeleteFunction
                  - cloudfront:PublishFunction
                  - cloudfront:GetFunction
                  - cloudfront:DescribeFunction
                Resource: "*"

              # ACM — create/validate certificate (for CloudFormation)
              - Sid: ACMManage
                Effect: Allow
                Action:
                  - acm:RequestCertificate
                  - acm:DeleteCertificate
                  - acm:DescribeCertificate
                  - acm:AddTagsToCertificate
                  - acm:ListTagsForCertificate
                Resource: "*"

              # Route 53 — lookup hosted zone + create DNS records
              - Sid: Route53Manage
                Effect: Allow
                Action:
                  - route53:ListHostedZones
                  - route53:ListHostedZonesByName
                  - route53:GetHostedZone
                  - route53:ChangeResourceRecordSets
                  - route53:GetChange
                  - route53:ListResourceRecordSets
                Resource: "*"

              # S3 — create/update bucket and policy (for CloudFormation)
              - Sid: S3BucketManage
                Effect: Allow
                Action:
                  - s3:CreateBucket
                  - s3:DeleteBucket
                  - s3:PutBucketPolicy
                  - s3:DeleteBucketPolicy
                  - s3:GetBucketPolicy
                  - s3:PutBucketPublicAccessBlock
                  - s3:PutEncryptionConfiguration
                  - s3:PutBucketVersioning
                  - s3:PutLifecycleConfiguration
                  - s3:GetLifecycleConfiguration
                  - s3:GetBucketVersioning
                  - s3:GetEncryptionConfiguration
                  - s3:GetBucketTagging
                  - s3:PutBucketTagging
                  - s3:GetBucketPublicAccessBlock
                Resource:
                  - !Sub "arn:aws:s3:::duckstore-spa-*"

      Tags:
        - Key: Project
          Value: DuckStore
        - Key: ManagedBy
          Value: CloudFormation

Outputs:
  RoleArn:
    Description: >
      ARN of the IAM Role — set this as the AWS_DEPLOY_ROLE_ARN secret in GitHub.
    Value: !GetAtt GitHubActionsDeployRole.Arn

  OIDCProviderArn:
    Description: ARN of the GitHub OIDC Identity Provider
    Value: !GetAtt GitHubOIDCProvider.Arn
