services:
  catalogdb:
    image: postgres

  basketdb:
    image: postgres

  distributedcache:
    image: redis

  orderdb:
    image: mcr.microsoft.com/mssql/server

  messagebroker:
    image: rabbitmq:management

  catalog.api:
    build:
      context: ./DuckStore.Services/Catalog/Catalog.API
      dockerfile: Dockerfile

  basket.api:
    build:
      context: ./DuckStore.Services/Basket/Basket.API
      dockerfile: Dockerfile

  discount.grpc:
    build:
      context: ./DuckStore.Services/Discount/Discount.Grpc
      dockerfile: Dockerfile

  ordering.api:
    build:
      context: ./DuckStore.Services/Ordering/Ordering.API
      dockerfile: Dockerfile

volumes:
  postgres_catalog:
  postgres_basket:
